# Generated by Django 3.0.3 on 2022-01-02 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('start', models.IntegerField()),
                ('stop', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pfam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_id', models.CharField(max_length=64)),
                ('domain_description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_id', models.CharField(max_length=64)),
                ('sequence', models.CharField(max_length=256)),
                ('length', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_id', models.CharField(max_length=64)),
                ('sequence', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxo_id', models.IntegerField()),
                ('clade', models.CharField(default='E', max_length=1)),
                ('genus', models.CharField(max_length=128)),
                ('species', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ProteinDomainLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domains', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proteins.Domains')),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proteins.Protein')),
            ],
            options={
                'unique_together': {('protein', 'domains')},
            },
        ),
        migrations.AddField(
            model_name='protein',
            name='domains',
            field=models.ManyToManyField(through='proteins.ProteinDomainLink', to='proteins.Domains'),
        ),
        migrations.AddField(
            model_name='protein',
            name='taxonomy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proteins.Taxonomy'),
        ),
        migrations.AddField(
            model_name='domains',
            name='pfam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proteins.Pfam'),
        ),
    ]
