# Generated by Django 3.0.3 on 2022-01-02 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='domains',
            unique_together={('description', 'start', 'stop')},
        ),
    ]
