# Generated by Django 3.0.3 on 2022-01-02 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0002_auto_20220102_1355'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='domains',
            unique_together={('pfam', 'start', 'stop')},
        ),
    ]
